[features]
seeds = true
skip-lint = false
[programs.localnet]
game_core = "9LqUvkM7zkVqpYypCRsuh5KitHbZZFrcfwkRVgirnnUf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/ellagoris/.config/solana/anchor.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
